# Generated by Django 2.0.7 on 2018-07-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(default='', max_length=100)),
                ('passWord', models.CharField(default='', max_length=100)),
                ('avatarUrl', models.URLField(default='')),
                ('city', models.CharField(default='', max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isRoot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField(default=1)),
                ('realName', models.CharField(default='', max_length=50)),
                ('phoneNum', models.CharField(default='', max_length=50)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('residue', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('firstFans', models.PositiveIntegerField(default=0)),
                ('secondFans', models.PositiveIntegerField(default=0)),
                ('avatarUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AgentApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realName', models.CharField(default='', max_length=100)),
                ('phoneNum', models.CharField(default='', max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(default='', max_length=20)),
                ('gender', models.PositiveSmallIntegerField(default=1)),
                ('province', models.CharField(default='', max_length=20)),
                ('avatarUrl', models.URLField()),
                ('status', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AgentCountDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('firstFans', models.PositiveSmallIntegerField(default=0)),
                ('secondFans', models.PositiveSmallIntegerField(default=0)),
                ('day', models.DateField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentProfitRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even', models.CharField(default='', max_length=50)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CartSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skuNum', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CashApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('applyTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=100)),
                ('label', models.CharField(default='', max_length=100)),
                ('fatherId', models.PositiveSmallIntegerField(default=0)),
                ('index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Collage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('effectiveTime', models.PositiveSmallIntegerField(default=12)),
                ('collagePeople', models.PositiveSmallIntegerField(default=2)),
                ('collageLimit', models.PositiveSmallIntegerField(default=1)),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('collageTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CollageSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collagePrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('collageNum', models.PositiveSmallIntegerField(default=1)),
                ('collage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Collage')),
            ],
        ),
        migrations.CreateModel(
            name='CollageUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCollage', models.BooleanField(default=False)),
                ('attendTime', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('collageNo', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAnonymous', models.BooleanField(default=True)),
                ('content', models.CharField(default='', max_length=300)),
                ('rate', models.PositiveSmallIntegerField(default=5)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.URLField(default='')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allSale', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('allUserNum', models.PositiveIntegerField(default=0)),
                ('allOrderNum', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CountMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('userNum', models.PositiveIntegerField(default=0)),
                ('orderNum', models.PositiveIntegerField(default=0)),
                ('month', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponType', models.PositiveSmallIntegerField(default=0)),
                ('fullAmount', models.PositiveSmallIntegerField(default=0)),
                ('reduceAmount', models.PositiveSmallIntegerField(default=0)),
                ('onceAmount', models.PositiveSmallIntegerField(default=0)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('disCountUpLimit', models.PositiveSmallIntegerField(default=0)),
                ('disCountDownLimit', models.PositiveSmallIntegerField(default=0)),
                ('couponNum', models.PositiveSmallIntegerField(default=0)),
                ('couponResNum', models.PositiveSmallIntegerField(default=0)),
                ('timeType', models.PositiveSmallIntegerField(default=0)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('perWeekDay', models.PositiveSmallIntegerField(default=0)),
                ('perMonthDay', models.PositiveSmallIntegerField(default=0)),
                ('userLimit', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MemberDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('memberName', models.CharField(default='', max_length=100)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('realTotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('createTime', models.DateTimeField()),
                ('prepay_id', models.CharField(default='', max_length=100)),
                ('out_trade_no', models.CharField(default='', max_length=100)),
                ('order_code', models.CharField(default='', max_length=100)),
                ('status', models.PositiveSmallIntegerField(default=9)),
                ('orderType', models.PositiveSmallIntegerField(default=0)),
                ('province', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('area', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=20)),
                ('phoneNum', models.CharField(default='', max_length=20)),
                ('express', models.CharField(default='', max_length=50)),
                ('expressNo', models.CharField(default='', max_length=50)),
                ('expressTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderSku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skuPrice', models.CharField(default='', max_length=20)),
                ('skuNum', models.PositiveSmallIntegerField(default=1)),
                ('skuName', models.CharField(default='', max_length=100)),
                ('productName', models.CharField(default='', max_length=100)),
                ('imgUrl', models.URLField(default='')),
                ('cartSkuId', models.PositiveSmallIntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picUrl', models.URLField(default='')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('isVideo', models.BooleanField(default=False)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgUrl', models.URLField(default='')),
                ('productName', models.CharField(default='', max_length=100)),
                ('categoryList', models.CharField(default='', max_length=100)),
                ('sellPoint', models.CharField(default='', max_length=50)),
                ('keyWords', models.CharField(default='', max_length=100)),
                ('introduce', models.TextField(default='', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('originPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('saleNum', models.PositiveIntegerField(default=0)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formatName', models.CharField(default='', max_length=100)),
                ('formatValue', models.CharField(default='', max_length=100)),
                ('index', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('even', models.CharField(default='', max_length=20)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('value', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(default='', max_length=100)),
                ('shopAddress', models.CharField(default='', max_length=200)),
                ('lat', models.CharField(default='0.000000', max_length=50)),
                ('lng', models.CharField(default='0.000000', max_length=50)),
                ('shopIntroduce', models.CharField(default='', max_length=300)),
                ('shopPhoneNum', models.CharField(default='', max_length=11)),
                ('shopSaleNum', models.PositiveIntegerField(default=0)),
                ('shopImgUrl', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SignDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residualNum', models.PositiveIntegerField(default=0)),
                ('sellPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('originPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('skuName', models.CharField(default='', max_length=100)),
                ('attrValueName', models.CharField(default='', max_length=100)),
                ('saleNum', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickName', models.CharField(default='', max_length=100)),
                ('gender', models.PositiveSmallIntegerField(default=1)),
                ('avatarUrl', models.URLField(blank=True, null=True)),
                ('phoneNum', models.CharField(default='', max_length=20)),
                ('createTime', models.DateTimeField()),
                ('openId', models.CharField(default='', max_length=100)),
                ('isAgent', models.BooleanField(default=False)),
                ('city', models.CharField(default='', max_length=100)),
                ('score', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('area', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=20)),
                ('phoneNum', models.CharField(default='', max_length=20)),
                ('isNormal', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User')),
            ],
        ),
        migrations.AddField(
            model_name='signday',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='scorerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='picture',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='ordersku',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SKU'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='order',
            name='userCoupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UserCoupon'),
        ),
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Order'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='collageuser',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='collageuser',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SKU'),
        ),
        migrations.AddField(
            model_name='collageuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='collagesku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='collagesku',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SKU'),
        ),
        migrations.AddField(
            model_name='cartsku',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SKU'),
        ),
        migrations.AddField(
            model_name='cartsku',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
        migrations.AddField(
            model_name='agentapply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.User'),
        ),
    ]
