# Generated by Django 2.0.7 on 2018-07-30 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='user',
            name='agent',
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='agentId',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='fansLevel',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
