# Generated by Django 2.0.7 on 2018-07-31 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180730_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashapply',
            old_name='total',
            new_name='cash',
        ),
        migrations.AddField(
            model_name='cashapply',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Agent'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashapply',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cashapply',
            name='phoneNum',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cashapply',
            name='wxCode',
            field=models.CharField(default='', max_length=50),
        ),
    ]
