# Generated by Django 2.0.7 on 2018-07-31 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='disCountDownLimit',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='userLimit',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
