# Generated by Django 2.0.7 on 2018-07-31 22:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180731_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
