# Generated by Django 2.0.7 on 2018-07-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_coupon_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
