# Generated by Django 2.0.7 on 2018-08-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_prepaytime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='prePayTime',
            new_name='payTime',
        ),
    ]
