# Generated by Django 2.0.7 on 2018-08-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180802_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prePayTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
