# Generated by Django 2.0.7 on 2018-08-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_prepaytime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstProfit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('firstLimit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('secondProfit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('secondLimit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
