# Generated by Django 2.0.7 on 2018-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_receivetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shopIntroduce',
            field=models.TextField(default=''),
        ),
    ]
