# Generated by Django 2.0.7 on 2018-08-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180802_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
