# Generated by Django 2.0.7 on 2018-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180802_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='fullAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='onceAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='reduceAmount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
