# Generated by Django 2.0.7 on 2018-08-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180802_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notifyStatus',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='disCountUpLimit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
