# Generated by Django 2.0.7 on 2018-08-03 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180803_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.SKU'),
            preserve_default=False,
        ),
    ]
