# Generated by Django 2.0.7 on 2018-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20180803_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='collagesku',
            name='residualNum',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='sharedStatus',
            field=models.BooleanField(default=False),
        ),
    ]
