# Generated by Django 2.0.7 on 2018-08-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20180804_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('userNum', models.PositiveIntegerField(default=0)),
                ('orderNum', models.PositiveIntegerField(default=0)),
                ('day', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CountMonth',
        ),
        migrations.AddField(
            model_name='cashapply',
            name='partner_trade_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='collageuser',
            name='collagerId',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='collageuser',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='collageTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='collagerId',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='expressCode',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
